#! /bin/csh -f
cp POSCAR tmp.vasp
#
set total_atoms_list = `awk 'NR==7{print $0}' tmp.vasp`
set count = 0
set total_atoms = 0
foreach i (${total_atoms_list})
  set total_atoms = `echo "${total_atoms} + $i" | bc`
  @ count += 1
end
echo "${total_atoms} S" > tmp.gen
#
awk 'NR==6{print $1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9}' tmp.vasp >> tmp.gen
#
set i = 1
set aj = 1
while ($i <= ${total_atoms})
  set jo = 1
  foreach j (${total_atoms_list})
    @ jo = $jo + $j
    if ($i == $jo) then
      @ aj = $aj + 1
    endif
  end
  awk -v ti=$i -v ai=$aj 'NR==(8+ti){print ti" "ai" "$1" "$2" "$3}' tmp.vasp >> tmp.gen
  @ i = $i + 1
end
#
echo '  0.000000000000000   0.000000000000000   0.000000000000000' >> tmp.gen
awk 'NR==3{print $0}' tmp.vasp >> tmp.gen
awk 'NR==4{print $0}' tmp.vasp >> tmp.gen
awk 'NR==5{print $0}' tmp.vasp >> tmp.gen
#
mv tmp.gen POS.gen
rm -f -r tmp.vasp

